---
- name: create directory layout
  file:
    path: "{{item.name}}"
    state: directory
    mode: "{{item.mode | default('0755')}}"
  with_items:
    - {name: 'clients.yml-revisions'}
    - {name: 'bin'}
    - {name: 'config'}
    - {name: 'config/remap.d'}
    - {name: 'config/banjax.d'}
    - {name: 'config/rundata'}
    - {name: 'config/logs'}
    - {name: 'config/conf.d'}
    - {name: 'config/gpg', mode: '0700'}
    - {name: 'config/ssl_multicert.d', mode: '0700'}
  tags:
    - init
    - setup

- name: check if autobrains_update.sh exists
  stat:
    path: "autobrains_update.sh"
  register: autobrains_update
  ignore_errors: True
  tags:
    - init
    - setup

- name: Create autobrains_update.sh script
  template:
    src: autobrains_update.sh.j2
    dest: "autobrains_update.sh"
    mode: '0755'
  when: not autobrains_update.stat.exists
  tags:
    - init
    - setup

- name: create blank clients.yml
  file:
    path: clients.yml
    state: touch
  tags:
    - init
    - setup

