---
- hosts: dashboard
  gather_facts: false

  roles:
    - {role: dashpull}

- hosts: letsencrypt
  become: true
  user: root

  # TODO: "le_skip: false" when in production and this is the only
  # controller accessing the letsencrypt server
  vars:
    le_skip: true

  vars_files:
    - clients.yml
    - override.yml
  tags:
    - letsencrypt
  roles:
    - {role: letsencrypt, tags: letsencrypt, when: le_skip == false}

- hosts: controller
  become: no

  vars_files:
    - clients.yml
    - override.yml

  tags:
    - controller
  roles:
    - {role: autobrains_update, tags: update}
    - {role: zonefile, tags: [zonefile, bind]}
    - {role: atsconf, tags: ats}
    - {role: lists, tags: lists}
