---
- hosts: dashboard
  gather_facts: false

  roles:
    - {role: dashpull}

- hosts: letsencrypt
  gather_facts: false

  # TODO: "le_skip: false" when in production and this is the only
  # controller accessing the letsencrypt server
  # Note: "le_skip: false" will still access letsencrypt server and
  # download existing certs already generated.
  vars:
    le_skip: false

  vars_files:
    - [ "clients.yml", "ph.yml" ]
    - [ "override.yml", "ph.yml" ]
  tags:
    - letsencrypt
  roles:
    - {role: letsencrypt, tags: letsencrypt}

- hosts: controller
  gather_facts: false

  vars_files:
    - [ "clients.yml", "ph.yml" ]
    - [ "override.yml", "ph.yml" ]

  tags:
    - controller
  roles:
    - {role: autobrains_update, tags: update}
    - {role: zonefile, tags: [zonefile, bind]}
    - {role: atsconf, tags: ats}
    - {role: lists, tags: lists}
