---
# TODO: the delegate_to: localhost needs to be thought out, [controller] ?
# TODO: the output directories probably needs to be outside playbook_dir root
# TODO: examine tags
# TODO: cert cleanup on dashboard?

- name: make sure needed directories exist
  file:
    path: "{{item}}"
    state: directory
    mode: '0750'
  delegate_to: localhost
  with_items:
    - clients.yml-revisions
    - "{{tls_home}}"
  tags:
    - clients_yml
    - tls_bundles

- name: remove controller clients.yml link
  file:
    path: clients.yml
    state: absent
  delegate_to: localhost 
  tags:
    - clients_yml

- name: get clients.yml
  fetch:
    src: "{{dash_clients_yml}}"
    dest: "clients.yml-revisions/clients.yml-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}"
    flat: true
  tags:
    - clients_yml

- name: Link clients.yml
  file:
    src: "clients.yml-revisions/clients.yml-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}"
    dest: clients.yml
    state: link
  delegate_to: localhost
  tags:
    - clients_yml

- name: check if clients.yml-revisions/clients.yml-last_used exists
  stat:
    path: clients.yml-revisions/clients.yml-last_used
  register: clientslast_used
  ignore_errors: true
  delegate_to: localhost
  tags:
    - clients_yml

- name: copy current clients.yml to clients.yml-last_used if none
  copy:
    src: "clients.yml-revisions/clients.yml-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}"
    dest: clients.yml-revisions/clients.yml-last_used
  when: not clientslast_used.stat.exists
  delegate_to: localhost
  tags:
    - clients_yml

- name: sync tls bundles from dashboard
  synchronize:
    mode: pull
    src: "{{tls_bundles_path}}/*.gpg"
    dest: "{{tls_home}}/encrypted"
    use_ssh_args: yes
    checksum: yes
  tags:
    - tls_bundles
