---

- name: make sure needed directories exist
  local_action:
    module: file
    path: "{{item}}"
    state: directory
    mode: '0750'
  with_items:
    - clients.yml-revisions
    - "{{tls_home}}"
  tags:
    - clients_yml
    - tls_bundles

- name: remove controller clients.yml link
  local_action:
    module: file
    path: clients.yml
    state: absent
  tags:
    - clients_yml

# TODO: This should be changed so we do not need gather_facts: true
# ie; ansible_date_time.year, etc.
- name: get clients.yml
  fetch:
    src: "{{dash_clients_yml}}"
    dest: "clients.yml-revisions/clients.yml-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}"
    flat: true
  tags:
    - clients_yml

# TODO: This should be changed so we do not need gather_facts: true
# ie; ansible_date_time.year, etc.
- name: Link clients.yml
  local_action:
    module: file
    src: "clients.yml-revisions/clients.yml-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}"
    dest: clients.yml
    state: link
  tags:
    - clients_yml

- name: check if clients.yml-revisions/clients.yml-last_used exists
  local_action:
    module: stat
    path: clients.yml-revisions/clients.yml-last_used
  register: clientslast_used
  ignore_errors: true
  tags:
    - clients_yml

# TODO: This should be changed so we do not need gather_facts: true
# ie; ansible_date_time.year, etc.
- name: copy current clients.yml to clients.yml-last_used if none
  local_action:
    module: copy
    src: "clients.yml-revisions/clients.yml-{{ansible_date_time.year}}{{ansible_date_time.month}}{{ansible_date_time.day}}{{ansible_date_time.hour}}{{ansible_date_time.minute}}{{ansible_date_time.second}}"
    dest: clients.yml-revisions/clients.yml-last_used
  when: not clientslast_used.stat.exists
  tags:
    - clients_yml

- name: sync tls bundles from dashboard
  synchronize:
    mode: pull
    src: "{{tls_bundles_path}}/*.gpg"
    dest: "{{tls_home}}/encrypted"
    use_ssh_args: yes
    checksum: yes
  tags:
    - tls_bundles
