---
- name: Setup ats output base directory
  file: path={{ats_output}} state=directory mode=0755
  tags:
    - ats 
    - setup

- name: Setup ats dnet output directories
  file: path={{ats_output}}{{item.key}} state=directory mode=0755
  with_dict: dnets
  tags:
    - ats 
    - setup

- name: Setup TLS upload output directory
  file: path={{tls_home}}/output/{{item.key}} state=directory mode=0755 recurse=yes
  with_dict: dnets
  tags:
    - ats
    - setup
    - tls

- name: Logging disabling
  template: src=logs_xml.config.j2 dest={{ats_output}}/{{item.key}}/logs_xml.config
  with_dict: dnets
  tags:
    - ats
    - ats_logging

- name: Logging disabling
  template: src=logging.config.j2 dest={{ats_output}}/{{item.key}}/logging.config
  with_dict: dnets
  tags:
    - ats
    - ats_logging

- name: register a bunch of intermedate loop values
  debug: var="do nothing"
  with_dict: "{{ remap }}"
  register: foo_result
  tags:
     - ats
     - ats_remap

- name: map over the registered stuff to make a proper list
  set_fact:
      site_list: "{{ foo_result.results | map(attribute='item.value') | list }}"
  tags:
     - ats
     - ats_remap

- name: create directory under /tmp for purge_remap genid files
  file:
      path: /tmp/purge_remap
      state: directory
      owner: www-data
      group: www-data
      mode: "0777"
  tags:
      - ats
      - ats_remap

- name: touch purge_remap genid files (non-additional-prefix)
  file:
      path: "/tmp/purge_remap/{{item.0['url']}}-{{item.1}}"
      state: touch
      mode: "0777"
  with_nested:
      - "{{ site_list }}"
      - [ 'http_no_www', 'http_www', 'https_no_www', 'https_www' ]
  tags:
      - ats
      - ats_remap

- name: touch purge_remap genid files (http + additional_prefix)
  file:
      path: "/tmp/purge_remap/{{item.0['url']}}-http_prefix-{{item.1}}"
      state: touch
      mode: "0777"
  with_subelements:
      - "{{ site_list | selectattr('additional_domain_prefix', 'defined') | list }}"
      - additional_domain_prefix
  tags:
      - ats
      - ats_remap

- name: touch purge_remap genid files (https + additional_prefix)
  file:
      path: "/tmp/purge_remap/{{item.0['url']}}-https_prefix-{{item.1}}"
      state: touch
      mode: "0777"
  with_subelements:
      - "{{ site_list | selectattr('additional_domain_prefix', 'defined') | list }}"
      - additional_domain_prefix
  tags:
      - ats
      - ats_remap

- name: remap config
  template: src=remap.config.j2 dest={{ats_output}}/{{item.key}}/remap.config
  with_dict: dnets
  tags:
    - ats
    - ats_remap

- name: cache.config 
  template: src=cache.config.j2 dest={{ats_output}}/{{item.key}}/cache.config
  with_dict: dnets
  tags: 
    - ats
    - ats_cache

- name: hosts.origin
  template: src=hosts.origin.j2 dest={{ats_output}}/{{item.key}}/hosts.origin
  with_dict: dnets
  tags: 
    - ats
    - ats_hosts

- name: ssl_multicert.config
  template: src=ssl_multicert.config.j2 dest={{ats_output}}/{{item.key}}/ssl_multicert.config
  with_dict: dnets
  tags:
    - ats
    - tls

- name: install uploaded certs
  command: scripts/tls_bundle_decrypt.sh {{item.key}} {{item.value["tls_bundle"]}} {{tls_home}} {{item.value.network}} {{tls_gpghome}}
  with_dict: remap
  when: item.value["tls_bundle"] is defined
  tags:
    - ats
    - tls
  ignore_errors: yes

- name: ip_allow.config
  template: src=ip_allow.config.j2 dest={{ats_output}}/{{item.key}}/ip_allow.config
  with_dict: dnets
  tags:
    - ats
    - ats_ip_allow

- name: write current timestamp to ats directory
  copy:
    dest: "{{ats_output}}/{{item.key}}/dashboard.timestamp"
    content: "{{timestamp}}\n"
  with_dict: dnets
  tags: ats
